soluti_sogenactif:
    resource: "@SolutiSogenactifBundle/Resources/config/routing.xml"
    prefix:   /payment

# Sonata Admin Routing
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

# HWI Oauth
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /oauth/connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /oauth/login

facebook_login:
    path: /oauth/login/check-facebook

# FOS User routing
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix:   /

# FOS JS routing
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

# Sonata Media
gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media

# Application routes
app:
    resource: "@AppBundle/Controller/"
    type:     annotation

app_blog:
    resource: "@XabenBlogBundle/Resources/config/routing.yml"
    prefix: /blog

# FOSO AuthServer routes

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"
